name = "GBPQAMDecoder"
authors = ["Felippe Alves"]

[deps]
DataPrep = "d40174be-394b-476a-94dd-cdf19e683a9d"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GBPAlgorithm = "52f5dfbb-b0c2-49ff-99e4-0d4f43f103e5"

[compat]
DrWatson = "2.13.0"
julia = "1.9.3"
